app = MaghsoudAhmadiAnvar-n8n
primary_region = "fra"

[build]
  image = "docker.n8n.io/n8nio/n8n:latest"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1    #always on & free

[[vm]]
  size = "shared-cpu-1x-256mb"
